### ISSUE TITLE
PreImagesRepresentative returns identity when it should return "fail" for trivial homomorphism

### ISSUE THREAD

**Issue by sTertooy** [gap-packages/polycyclic#39]
It seems that `PreImagesRepresentative` consistently returns `id` when the homomorphism maps every element of the source to the identity of the range. A minimal working example:
```
gap> G := AbelianPcpGroup( [ 2 ] );
Pcp-group with orders [ 2 ]
gap> phi := GroupHomomorphismByImages( G, G, [ G.1 ], [ Identity( G ) ] );
[ g1 ] -> [ id ]
gap> PreImagesRepresentative( phi, G.1 );
id
```
This does not happen for non-trivial homomorphisms:
```
gap> G := AbelianPcpGroup( [ 2, 2 ] );
Pcp-group with orders [ 2, 2 ]
gap> phi := GroupHomomorphismByImages( G, G, [ G.1, G.2 ], [ Identity( G ), G.2 ] );
[ g1, g2 ] -> [ id, g2 ]
gap> PreImagesRepresentative( phi, G.1 );
fail
```
I've tested versions 2.10, 2.13.1, 2.14, 2.15.1 and the current master; all of these have this bug.

For now, I've been able to circumvent this bug by wrapping `PreImagesRepresentative( hom, g )` in a conditional statement that checks if `g` lies in `Image( hom )`.

**Comment by fingolfin** [comment]
Thank you for your report! This should be fixed by https://github.com/gap-packages/polycyclic/pull/41
